### ISSUE TITLE
Syntax error message when using the controls/fcontrols options

### ISSUE THREAD

**Issue by martinmoreno70** [leojahrens/scatterfit#3]
Hi Leo,

I am getting a syntax error each time I add the controls/fcontrols options. After looking at the code, it seems there is an issue with a direct call to subset a results matrix which Stata seems unable to deal with. For that reason, I created a copy of the results matrix and change the subsequent lines to call the copy of the matrix. After this fix, the ado runs without error. 
Let me know if this makes sense. 

Current code in lines 611-613
			replace cil`bynum2' = r(table)[5,`num'] if _n==`num'
			replace ciu`bynum2' = r(table)[6,`num'] if _n==`num'
			replace pe`bynum2' = r(table)[1,`num'] if _n==`num'
Suggested code:
			mat def copyrtable = r(table)
			replace cil`bynum2' = copyrtable[5,`num'] if _n==`num'
			replace ciu`bynum2' = copyrtable[6,`num'] if _n==`num'
			replace pe`bynum2' = copyrtable[1,`num'] if _n==`num'

**Comment by leojahrens** [comment]
Hi Martin,

thanks for the message! The code you suggest works, but the original code works just as well on my end. I would like to understand where your error comes from before implementing changes, among other things because these are not the only lines that draw results from a r(table). What data are you using? And what version of Stata are you running? 

Many problems associated with scatterfit result from the (way too many) dependencies it has. Could you try re-downloading reghdfe, gtools, and ftools and check whether your problem persists?

Also: it was quite cumbersome to copy your code because the line breaks and declaration of it as code is somehow not working. Don't worry, no problem, better let you know I thought.

Best wishes,
Leo
