### ISSUE TITLE
error: option local() not allowed

### ISSUE THREAD

**Issue by whuxuan** [leojahrens/scatterfit#4]
Hi Leo, thank you so much for your work on this package. I recently installed it on my laptop (WIN10, STATA17 MP), but kept getting the error saying "option local() not allowed)". I tried different datasets and used the simplest command without adding any options and the error is persistent. Could you please provide any guidance on this?

**Comment by leojahrens** [comment]
Hi whuxuan,

thank you for your report! This is highly appreciated.

The command works perfectly on several of my computers running different versions of Stata. But I would really like to find out what the problem is in your case. Could you try the following solutions? 

- Update gtools via "gtools, upgrade"
- Update scatterfit via "ssc install scatterfit, replace"
- Then try using the package
- If it doesn't work, try running the command with the "slow" option

Please report back to me if this helps. I have some other ideas, but maybe it is this simple.

Best wishes,
Leo

**Comment by whuxuan** [comment]
Hi Leo,

Thank you so much for your reply! Apologies for my slow response. I have addressed the problem by reinstalling palettes, colrspace, and blindschemes. Not sure which one of them led to the the problem, though. 

Best,
Zhenxuan

**Comment by leojahrens** [comment]
I am happy to hear that!
